use std::time::Instant;
pub fn or_test() {
    let mut count = 1000;
    let start = Instant::now();
    while count > 0 {
        if true
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
            | false
        {
            count -= 1;
        }
    }
    let duration = start.elapsed();
    println!("1000 |: {:?}", duration);

    let mut count = 1000;
    let start = Instant::now();
    while count > 0 {
        if true
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
            || false
        {
            count -= 1;
        }
    }
    let duration = start.elapsed();
    println!("1000 ||: {:?}", duration);

    let start = Instant::now();
    if !(false & false & false & false) {
        println!("1 &: {:?}", start.elapsed());
    }

    let start = Instant::now();
    if !(false && false && false && false) {
        println!("1 &&: {:?}", start.elapsed());
    }
}
