FROM python:slim
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY . .

CMD ["bash", "-c", "echo '\e[36Goooooooooooooooooood morning Vietnam!\e[0m::DEV' && exec bash"]
